<template>
  <div style="background-color: #000 !important">
    <b-container class="p-3 pt-2 pt-md-4">
      <b-row align-h="center" class="text-center pt-5 mt-5 mt-md-3">
        <b-col>
          <h1 class="title text-white">TERMS & CONDITIONS</h1>
        </b-col>
      </b-row>

      <div class="about text-white pt-2 pt-md-4">
        <p>
          The Heist is a collection of digital artworks (NFTs) running on the
          Ethereum network. This website is only an interface allowing
          participants to exchange digital collectibles. Users are entirely
          responsible for the safety and management of their own private
          Ethereum wallets and validating all transactions and contracts
          generated by this website before approval. Furthermore, as The Heist
          smart contract runs on the Ethereum network, there is no ability to
          undo, reverse, or restore any transactions.
        </p>
        <p>
          This website and its connected services are provided “as is” and “as
          available” without warranty of any kind. By using this website you are
          accepting sole responsibility for any and all transactions involving
          The Heist digital collectibles.
        </p>
        <h1 class="title">OWNERSHIP</h1>
        <ol type="I">
          <li>
            You Own the NFT. Each Identity* is an NFT on the Ethereum
            blockchain. When you purchase an NFT, you own the underlying
            Identity*, the Art, completely. Ownership of the NFT is mediated
            entirely by the Smart Contract and the Ethereum Network: at no point
            may we seize, freeze, or otherwise modify the ownership of any
            Identity*.
          </li>
          <li>
            Personal Use. Subject to your continued compliance with these Terms,
            The Heist LLC grants you a worldwide, royalty-free license to use,
            copy, and display the purchased Art, along with any extensions that
            you choose to create or use, solely for the following purposes: (i)
            for your own personal, non-commercial use; (ii) as part of a
            marketplace that permits the purchase and sale of your Identity* /
            NFT, provided that the marketplace cryptographically verifies each
            Heist Identity* owner’s rights to display the Art for their Heist
            Identity* to ensure that only the actual owner can display the Art;
            or (iii) as part of a third party website or application that
            permits the inclusion, involvement, or participation of your
            Identity*, provided that the website/application cryptographically
            verifies each The Heist Identity* owner’s rights to display the Art
            for their Heist Identity* to ensure that only the actual owner can
            display the Art, and provided that the Art is no longer visible once
            the owner of The Heist Identity* leaves the website/application.
          </li>
          <li>
            Other than the rights to the Art, nothing herein gives you any
            rights to any other trademarks or other intellectual property rights
            belonging to The Heist. All of these rights are expressly reserved
            in the name of The Heist LLC.
          </li>
          <li>
            Feedback. You may choose to submit comments, bug reports, ideas or
            other feedback about the Site, including without limitation about
            how to improve the Site (collectively, “Feedback”). By submitting
            any Feedback, you agree that we are free to use such Feedback in any
            way we choose without additional compensation to you and you hereby
            grant us a perpetual, irrevocable, nonexclusive, worldwide license
            to incorporate and use the Feedback for any purpose.
          </li>
        </ol>
        <div class="d-flex">
          <h3 class="font-weight-bold text-danger"><i>Identity</i></h3>
          <p class="ml-3 pt-1">
            is the term we use to describe the female form of your NFT. I mean,
            you have to change your identity before a heist... right?
          </p>
        </div>
      </div>
    </b-container>
  </div>
</template>
<script>
export default {
  layout: "main",
};
</script>
<style scoped>
@font-face {
  font-family: "Abys";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("~assets/fonts/abys-regular.otf") format("truetype");
}

@font-face {
  font-family: "komik";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("~assets/fonts/komik.ttf") format("truetype");
}

@font-face {
  font-family: "Champange";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("~assets/fonts/Champagne.ttf") format("truetype");
}

.about {
  font-family: "Champange";
  font-size: 22px;
}
.title {
  font-family: "komik";
  font-size: 3rem;
}
.shit {
  padding-top: 2rem;
}
</style>
